In [158]:
!pip install geneticalgorithm

In [159]:
from geneticalgorithm import geneticalgorithm as ga

import numpy as np
np.random.seed(43958734)

In [160]:
#Este método realiza un iteración de un autómata celular unidimensional a una CI según la regla dada
def iteracionAutomataUnidimensional(CI,rule):
  next = list()
  for i in range(len(CI)):
    c = CI[i]
    if i==len(CI)-1:
      vd = CI[0]
    else: 
      vd = CI[i+1]
    if i==0:
      vi = CI[len(CI)-1]
    else: 
      vi = CI[i-1]

    #Con el siguiente bloque if sacamos cuál será el valor de c en el siguiente paso según la regla
    if vi==1 and c==1 and vd==1:
      next.append(rule[0])
    elif vi==1 and c==1 and vd==0:
      next.append(rule[1])
    elif vi==1 and c==0 and vd==1:
      next.append(rule[2])
    elif vi==1 and c==0 and vd==0:
      next.append(rule[3])
    elif vi==0 and c==1 and vd==1:
      next.append(rule[4])
    elif vi==0 and c==1 and vd==0:
      next.append(rule[5])
    elif vi==0 and c==0 and vd==1:
      next.append(rule[6])
    elif vi==0 and c==0 and vd==0:
      next.append(rule[7])

  return next

In [161]:
#Este método realiza un iteración de un autómata celular bidimensional a una CI según la regla dada como [3,3,2,4] -> B3S24
def iteracionAutomataBidimensional(CI,rule):
  next = list()
  nRows = len(CI)
  nCols = len(CI[0])

  for i in range(nRows):
    newRow = list()
    for j in range(nCols):
      c = CI[i][j]

      if j==0:#Células del borde izquierdo
        v3 = CI[i][nCols-1]
        v4 = CI[i][j+1]
        if i==0:#Célula de la izquierda-arriba
          v0 = CI[nRows-1][nCols-1]
          v1 = CI[nRows-1][j]
          v2 = CI[nRows-1][j+1]
          v5 = CI[i+1][nCols-1]
          v6 = CI[i+1][j]
          v7 = CI[i+1][j+1]
        elif i==nRows-1:#Célula de la izquierda-abajo
          v0 = CI[i-1][nCols-1]
          v1 = CI[i-1][j]
          v2 = CI[i-1][j+1]
          v5 = CI[0][nCols-1]
          v6 = CI[0][j]
          v7 = CI[0][j+1]
        else:
          v0 = CI[i-1][nCols-1]
          v1 = CI[i-1][j]
          v2 = CI[i-1][j+1]
          v5 = CI[i+1][nCols-1]
          v6 = CI[i+1][j]
          v7 = CI[i+1][j+1]
      elif j==nCols-1:#Células del borde derecho
        v3 = CI[i][j-1]
        v4 = CI[i][0]
        if i==0:#Célula de la derecha-arriba
          v0 = CI[nRows-1][j-1]
          v1 = CI[nRows-1][j]
          v2 = CI[nRows-1][0]
          v5 = CI[i+1][j-1]
          v6 = CI[i+1][j]
          v7 = CI[i+1][0]
        elif i==nRows-1:#Célula de la derecha-abajo
          v0 = CI[i-1][j-1]
          v1 = CI[i-1][j]
          v2 = CI[i-1][0]
          v5 = CI[0][j-1]
          v6 = CI[0][j]
          v7 = CI[0][0]
        else:
          v0 = CI[nRows-1][j-1]
          v1 = CI[nRows-1][j]
          v2 = CI[nRows-1][0]
          v5 = CI[i+1][j-1]
          v6 = CI[i+1][j]
          v7 = CI[i+1][0]
      elif i==0:#Células del borde superior
        v0 = CI[nRows-1][j-1]
        v1 = CI[nRows-1][j]
        v2 = CI[nRows-1][j+1]
        v3 = CI[i][j-1]
        v4 = CI[i][j+1]
        v5 = CI[i+1][j-1]
        v6 = CI[i+1][j]
        v7 = CI[i+1][j+1]
      elif i==nRows-1:#Células del borde inferior
        v0 = CI[i-1][j-1]
        v1 = CI[i-1][j]
        v2 = CI[i-1][j+1]
        v3 = CI[i][j-1]
        v4 = CI[i][j+1]
        v5 = CI[0][j-1]
        v6 = CI[0][j]
        v7 = CI[0][j+1]
      else:#Células que no están en los bordes
        v0 = CI[i-1][j-1]
        v1 = CI[i-1][j]
        v2 = CI[i-1][j+1]
        v3 = CI[i][j-1]
        v4 = CI[i][j+1]
        v5 = CI[i+1][j-1]
        v6 = CI[i+1][j]
        v7 = CI[i+1][j+1]

      num1s = v0 + v1 + v2 + v3 + v4 + v5 + v6 + v7

      #Con el siguiente bloque if sacamos cuál será el valor de c en el siguiente paso según la regla
      if c==0 and (num1s>=rule[0] and num1s<=rule[1]):#Nace
        newRow.append(1)
      elif c==1 and (num1s>=rule[2] and num1s<=rule[3]):#Sobrevive
        newRow.append(1)
      else:
        newRow.append(0)
    next.append(newRow)
  return next

In [162]:
#Este método genera un número de CIs aleatoriamente para autómatas unidimensionales
def generarCIs(num):
  CIs = []
  for i in range(num):
    n = np.random.randint(10,30)
    CI = np.random.randint(0,2,size=n)
    CIs.append(CI)
  return CIs

In [163]:
#Este método genera un número de CIs aleatoriamente para autómatas bidimensionales
def generarCIs2D(num):
  CIs = []
  for i in range(num):
    n = np.random.randint(10,30)
    m = np.random.randint(10,30)
    CI = np.random.randint(0,2,size=(n,m))
    CIs.append(CI)
  return CIs

In [164]:
#-----------------------------------------------Ejercicio 1------------------------------------------------------
#Con esta función obtenemos el valor p, el cual es el porcentaje de 1s de la configuración inicial
def porcentaje1s(CI):
  ones=0
  for c in CI:
    if c==1:
      ones = ones+1
  p = ones/len(CI)
  return p

In [165]:
#Con este método aplicamos una regla a una configuración inicial un máximo de Tmax veces, si se llega al objetivo se devuelve True
def llegarObjEj1(CI,rule):
  Tmax = 15 #Máximo número de iteraciones
  pInicial = porcentaje1s(CI)
  #print("Configuración inicial: {0}".format(CI))
 
  for t in range(Tmax):
    next = iteracionAutomataUnidimensional(CI,rule)

    #print("Iteración {0}: {1}".format(t,next))
    p = porcentaje1s(next)
    if (pInicial < 0.5 and p==0) or (pInicial > 0.5 and p==1) or (pInicial==0.5 and (p==0 or p==1)): #Comprobamos si se cumple el objetivo
      #print("Configuración objetivo: todo a {0}s en {1} paso(s)".format(int(p),t+1))
      return True
    elif np.array_equal(CI,next): #Si se queda estancado en el mismo estado, se para la ejecución
      #print("No se ha logrado llegar a la configuración objetivo, el automata se queda atascado en el mismo estado")
      return False
    else:
      CI = next

  #print("No se ha logrado llegar a la configuración objetivo en {0} paso(s)".format(Tmax))
  return False

In [166]:
#Este método permite puntuar una regla como el porcentaje de CIs que lleva al objetivo
def valorarReglaEj1(rule,CIs):
  val = 0
  casoRes = -1
  bonificación2Casos = False
  for CI in CIs:
    p = porcentaje1s(CI)
    #print("P: {0}".format(p))
    if llegarObjEj1(CI,rule):
      val = val + 1
      if casoRes == -1:
        if p<0.5:
          casoRes = 0
        elif p>0.5:
          casoRes = 1
      elif not bonificación2Casos and ((p<0.5 and casoRes==1) or (p>0.5 and casoRes==0)):
        #print("Resuelve ambos casos")
        bonificación2Casos = True
  valoración = val/len(CIs)
  if bonificación2Casos:
    return valoración*4
  else:
    return valoración

In [167]:
def funciónObjetivoEj1(rule):
  #print("Regla: {0}".format(rule))
  return -valorarReglaEj1(rule,CIs)

algorithm_param = {'max_num_iteration': 1,\
                   'population_size':20,\
                   'mutation_probability':0.3,\
                   'elit_ratio': 0.05,\
                   'crossover_probability': 0.5,\
                   'parents_portion': 0.3,\
                   'crossover_type':'uniform',\
                   'max_iteration_without_improv':None}

modelEj1=ga(function=funciónObjetivoEj1,dimension=8,variable_type='bool',algorithm_parameters=algorithm_param,progress_bar=False,convergence_curve=False)

In [168]:
for i in range(10):
    CIs = generarCIs(100)
    modelEj1.run()

 The best solution found:
 [1. 0. 0. 0. 1. 0. 0. 0.]

 Objective function:
 -0.51
 The best solution found:
 [1. 1. 1. 1. 1. 1. 1. 0.]

 Objective function:
 -2.04
 The best solution found:
 [1. 1. 1. 1. 1. 0. 1. 0.]

 Objective function:
 -0.54
 The best solution found:
 [1. 0. 1. 0. 1. 0. 0. 0.]

 Objective function:
 -0.6
 The best solution found:
 [1. 1. 1. 1. 1. 0. 0. 1.]

 Objective function:
 -0.59
 The best solution found:
 [0. 0. 1. 1. 0. 1. 1. 1.]

 Objective function:
 -0.2
 The best solution found:
 [0. 1. 1. 1. 1. 1. 1. 0.]

 Objective function:
 -0.6
 The best solution found:
 [1. 1. 0. 1. 1. 0. 1. 1.]

 Objective function:
 -0.17
 The best solution found:
 [1. 1. 1. 0. 1. 1. 1. 0.]

 Objective function:
 -0.62
 The best solution found:
 [1. 1. 1. 0. 1. 0. 1. 1.]

 Objective function:
 -0.54


In [186]:
#Mejores reglas encontradas para el Ej1: [0,1,1,1,1,1,1,1], [0,0,0,0,0,1,1,1], [0,1,1,1,1,1,1,0], [0,0,0,1,0,1,0,1], [0,1,1,1,1,0,1,0], [0,1,0,1,0,1,1,1]

CIs = generarCIs(100)
valorarReglaEj1([0,1,1,1,1,1,1,1],CIs)#Comentar la bonificación al resultado para porcentajes reales

1.08

In [170]:
#-----------------------------------------------Ejercicio 2------------------------------------------------------
#Con esta función sabemos si configuración inicial tiene un número par de 1s o no
def num1sPar(CI):
  res=True
  for row in CI:
    for c in row:
      if c==1:
        res = not res
  return res

In [171]:
#Con esta función obtenemos el valor p, el cual es el porcentaje de 1s para una configuración inicial bidimensional
def porcentaje1sBidimensional(CI):
  ones=0
  for row in CI:
    for c in row:
      if c==1:
        ones = ones+1
  p = ones/(len(CI)*len(CI[0]))
  return p

In [172]:
#Con este método aplicamos una regla a una configuración inicial un máximo de Tmax veces, si se llega al objetivo se devuelve True
def llegarObjEj2(CI,rule):
  Tmax = 100 #Máximo número de iteraciones 
  objTodo1 = num1sPar(CI)
  #print("Configuración inicial: {0}".format(CI))
 
  for t in range(Tmax):
    next = iteracionAutomataBidimensional(CI,rule)

    #print("Iteración {0}:".format(t))
    #for i in next:
    #  for j in i:
    #    print(j, end=" ")
    #  print()
    p = porcentaje1sBidimensional(next)
    if (objTodo1 and p==1) or (not objTodo1 and p==0): #Comprobamos si se cumple el objetivo
      #print("Configuración objetivo: alcanzada en {0} paso(s)".format(t+1))
      return True
    elif np.array_equal(CI,next): #Si se queda estancado en el mismo estado, se para la ejecución
      #print("No se ha logrado llegar a la configuración objetivo, el automata se queda atascado en el mismo estado")
      return False
    else:
      CI = next

  #print("No se ha logrado llegar a la configuración objetivo en {0} paso(s)".format(Tmax))
  return False

In [173]:
#Este método permite puntuar una regla como el porcentaje de CIs que lleva al objetivo
def valorarReglaEj2(rule,CIs):
  val = 0

  #Con las siguientes líneas hacemos que reglas como [3,1,4,2] sean [1,3,2,4], siguiendo la definición dada 
  if rule[0]>rule[1]:
    a = rule[0]
    rule[0] = rule[1]
    rule[1] = a
  if rule[2]>rule[3]:
    a = rule[2]
    rule[2] = rule[3]
    rule[3] = a

  for CI in CIs:
    objTodo1 = num1sPar(CI)
    #print("P: {0}".format(p))
    if llegarObjEj2(CI,rule):
      val = val + 1

  valoración = val/len(CIs)
  return valoración

In [174]:
def funciónObjetivoEj2(rule):
  #print("Regla: {0}".format(rule))
  return -valorarReglaEj2(rule,CIs)

algorithm_param = {'max_num_iteration': 1,\
                   'population_size':20,\
                   'mutation_probability':0.3,\
                   'elit_ratio': 0.05,\
                   'crossover_probability': 0.5,\
                   'parents_portion': 0.3,\
                   'crossover_type':'uniform',\
                   'max_iteration_without_improv':None}

bondaries = np.array([[0,8]]*4)#Los genes podrán tener valores entre 0 y 8

modelEj2=ga(function=funciónObjetivoEj2,dimension=4,variable_type='int',variable_boundaries=bondaries,algorithm_parameters=algorithm_param,progress_bar=False,convergence_curve=False)

In [175]:
for i in range(3):
    CIs = generarCIs2D(30)
    modelEj2.run()

 The best solution found:
 [0. 7. 4. 0.]

 Objective function:
 -0.9333333333333333
 The best solution found:
 [5. 0. 0. 6.]

 Objective function:
 -0.9666666666666667
 The best solution found:
 [0. 3. 1. 1.]

 Objective function:
 -0.9333333333333333


In [176]:
#Soluciones: [0,2,0,0] [0,7,1,5] (0.99) [0,6,0,5] [0,6,1,5] [0,6,2,5] [0,8,0,4] (0.98)
CIs = generarCIs2D(100)
valorarReglaEj2([0,2,0,0],CIs)#Comentar la bonificación al resultado para porcentajes reales

0.99

In [177]:
#-----------------------------------------------Ejercicio 3------------------------------------------------------
#Con esta función sabemos si configuración inicial solo tiene un 1 y todo lo demás a 0
def tieneSoloUn1(CI):
  res=False
  for c in CI:
    if res==False and c==1:
      res = True
    elif c==1:
      return False
  return res

In [178]:
#Con este método aplicamos una regla a una configuración inicial un máximo de Tmax veces, si se llega al objetivo se devuelve True
def llegarObjEj3(CI,rule):
  Tmax = 20 #Máximo número de iteraciones 
  objTodo1 = tieneSoloUn1(CI)
  #print("Configuración inicial: {0}".format(CI))
 
  for t in range(Tmax):
    next = iteracionAutomataUnidimensional(CI,rule)

    #print("Iteración {0}: {1}".format(t,next))
    p = porcentaje1s(next)
    if (objTodo1 and p==1) or (not objTodo1 and p==0): #Comprobamos si se cumple el objetivo
      #print("Configuración objetivo: alcanzada en {0} paso(s)".format(t+1))
      return True
    elif np.array_equal(CI,next): #Si se queda estancado en el mismo estado, se para la ejecución
      #print("No se ha logrado llegar a la configuración objetivo, el automata se queda atascado en el mismo estado")
      return False
    else:
      CI = next

  #print("No se ha logrado llegar a la configuración objetivo en {0} paso(s)".format(Tmax))
  return False

In [179]:
#Este método permite puntuar una regla como el porcentaje de CIs que lleva al objetivo
def valorarReglaEj3(rule,CIs):
  val = 0
  casoRes = -1
  bonificación2Casos = False
  for CI in CIs:
    objTodo1 = tieneSoloUn1(CI)
    #print("P: {0}".format(p))
    if llegarObjEj3(CI,rule):
      val = val + 1
      if casoRes == -1:
        if objTodo1:
          casoRes = 1
        else:
          casoRes = 0
      else:
        if not bonificación2Casos and ((not objTodo1 and casoRes==1) or (objTodo1 and casoRes==0)):
          #print("Resuelve ambos casos")
          bonificación2Casos = True
  valoración = val/len(CIs)
  if bonificación2Casos:
    return valoración*2  
  else:
    return valoración

In [180]:
def funciónObjetivoEj3(rule):
  #print("Regla: {0}".format(rule))
  return -valorarReglaEj3(rule,CIs)

algorithm_param = {'max_num_iteration': 1,\
                   'population_size':20,\
                   'mutation_probability':0.3,\
                   'elit_ratio': 0.05,\
                   'crossover_probability': 0.5,\
                   'parents_portion': 0.3,\
                   'crossover_type':'uniform',\
                   'max_iteration_without_improv':None}

modelEj3=ga(function=funciónObjetivoEj3,dimension=8,variable_type='bool',algorithm_parameters=algorithm_param,progress_bar=False,convergence_curve=False)

In [181]:
for i in range(5):
    CIs = generarCIs(100)
    #Aleatoriamente es muy dificil obtener una CI que su objetivo sea llegar a 0, las añadiremos a mano
    for k in range(20):
      CIs.extend([[0,0,0,1,0,0,0],[1,0,0,0],[0,1,0,0,0],[0,0,0,0,0,0,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]])
    modelEj3.run()

 The best solution found:
 [0. 0. 0. 0. 1. 0. 0. 0.]

 Objective function:
 -0.5
 The best solution found:
 [0. 1. 1. 1. 0. 1. 1. 1.]

 Objective function:
 -1.04
 The best solution found:
 [0. 1. 1. 1. 1. 1. 1. 1.]

 Objective function:
 -1.21
 The best solution found:
 [0. 1. 1. 1. 1. 1. 1. 1.]

 Objective function:
 -1.27
 The best solution found:
 [0. 1. 1. 1. 1. 1. 1. 1.]

 Objective function:
 -1.25


In [187]:
#Se encuentran reglas que son solución del problema: [0,1,1,1,1,1,1,1] (0.6) [0,1,0,1,0,1,1,1] [0,0,0,1,1,1,1,1] [0,0,0,1,0,1,0,1] (0.58) [0,0,0,0,0,1,1,1] (0.56)
CIs = generarCIs(100)
for k in range(20):
      CIs.extend([[0,0,0,1,0,0,0],[1,0,0,0],[0,1,0,0,0],[0,0,0,0,0,0,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]])
valorarReglaEj3([0,1,1,1,1,1,1,1],CIs)#Comentar la bonificación al resultado para porcentajes reales

1.23